### ISSUE TITLE
UI_

### ISSUE THREAD

**Issue by ghost** [Double-Fine-Game-Club/amnesia-adventure#41]
UI_ seems to handle conversion of underscores to spaces however in the UI it displays this. Proposed change to demonstrate this behavior and a heads up that the prefix isn't being handled uniformly in this area.
Before:
![godot](https://user-images.githubusercontent.com/26851121/30236218-872e4c8e-94c9-11e7-896e-5b7ae161a512.png)
After:
![image](https://user-images.githubusercontent.com/26851121/30236225-9db02310-94c9-11e7-9d23-c7b66c4a3bbf.png)

I am curious if this is a breaking change for anyone else though. Not clear if spaces are a no go for a reason I'm unaware of.

**Comment by fleskesvor** [comment]
@etisdew The way the localization framework is supposed to work is that text strings are put in a csv file, `translations/general.csv` in our case, and they are then imported by pressing the `Import` button at the top left and then `Translations` to access the `Import Translations` UI. From there you set the csv file from before as the source, a target path (`translations/` in our case), and then you mark which of the available languages from the source you want to import. Then when you click `Import`, Godot creates the xl files, which are used by the game.

At the moment, I think there are two issues with `general.csv`, which are causing issues when importing.

1. The line with the UI_NEW_GAME_CONFIRM id has some junk characters in it, and also a trailing comma, which might explain why it isn't being read/found by the translation framework.
2. The last translation is missing an id, which causes the English translation to be used as id*, the French is used as the English, Spanish as French, so that there's no translation for Spanish.

*In general, I don't think it's a good idea to use strings with spaces as ids, but that's an issue for another time.

If you want to take a stab at fixing this, that would be great. It might be a good idea to delete or move the current xl files before you try to import the fixed file, and also try to just import English first, since the editor has a tendency to throw a fit when it encounters problems during import.

Let me know if anything needs more clarification and thanks for helping out. :smile:

**Comment by ghost** [comment]
I've fixed the initial issue by referencing the ammended csv, moving to the spanish translation issue godot is angry at me for trying to get Spanish. I don't see what the issue is. I can get it to run or compile to editor. -_- Used both hands and a foot to get this screen shot. lol

![sdf](https://user-images.githubusercontent.com/26851121/30245648-9f8a2d62-9595-11e7-9cc1-54e81132a9bb.png)

It was just a missing value on the last line.

**Comment by fleskesvor** [comment]
Yep, that's the sort of stuff that makes Godot throw a fit during import of translations. :wink: This looks good now. :+1:
