### ISSUE TITLE
Migrate scenes to new .tscn format

### ISSUE THREAD

**Issue by fleskesvor** [Double-Fine-Game-Club/amnesia-adventure#9]
It would be great to change all binary .scn files to the new text-based .tscn format, since it is better suited for tracking changes with version control. This might be a bit tricky though, since it is easy to break dependencies because of .scn files referenced by name in code.

**Comment by JenniBee** [comment]
flesk did the large bulk of this in #14 - the rest of the things blocking this are related to bugs in Godot.  Since Godot is being re-written for 3.0, we'll need to adapt the code for 3.0 once that's out - and that's a whole other can of worms.

At the moment though, as it stands, the bugs in Godot makes it impossible to go further with this, so I'm going to close this.
